<?php

declare(strict_types=1);

namespace Tests\Application;

use PHPUnit\Framework\TestCase;
use SeedWork\Application\IntegrationEvent;

final class IntegrationEventTest extends TestCase
{
    private function makeEvent(string $id = '', ?\DateTimeImmutable $occurredAt = null): IntegrationEvent
    {
        return new readonly class(
            type: 'test.event',
            version: '1.0',
            aggregateId: 'agg-1',
            payload: [],
            correlationId: 'corr-1',
            id: $id,
            occurredAt: $occurredAt ?? new \DateTimeImmutable('now', new \DateTimeZone('UTC')),
        ) extends IntegrationEvent {};
    }

    public function testIdIsAutoGeneratedWhenNotProvided(): void
    {
        $event = $this->makeEvent();

        $this->assertNotEmpty($event->id);
        $this->assertStringStartsWith('evt-', $event->id);
    }

    public function testTwoAutoGeneratedIdsAreUnique(): void
    {
        $event1 = $this->makeEvent();
        $event2 = $this->makeEvent();

        $this->assertNotSame($event1->id, $event2->id);
    }

    public function testExplicitIdIsPreserved(): void
    {
        $event = $this->makeEvent(id: 'my-custom-id');

        $this->assertSame('my-custom-id', $event->id);
    }

    public function testOccurredAtDefaultsToUtcNow(): void
    {
        $before = new \DateTimeImmutable('now', new \DateTimeZone('UTC'));
        $event = new readonly class(
            type: 'test.event',
            version: '1.0',
            aggregateId: 'agg-1',
            payload: [],
            correlationId: 'corr-1',
        ) extends IntegrationEvent {};
        $after = new \DateTimeImmutable('now', new \DateTimeZone('UTC'));

        $this->assertGreaterThanOrEqual($before, $event->occurredAt);
        $this->assertLessThanOrEqual($after, $event->occurredAt);
        $this->assertSame('UTC', $event->occurredAt->getTimezone()->getName());
    }
}
