name: Devcontainer

on:
  pull_request:
    paths:
    - .devcontainer/**

permissions:
  contents: read

jobs:
  build-and-check:
    name: Build image and run checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Build devcontainer and run quality checks
      uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
      with:
        push: never
        runCmd: make install check test-examples
