name: Quality

on:
  workflow_call:

permissions:
  contents: read

jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Set up PHP 8.4
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        php-version: 8.4
        coverage: xdebug

    - name: Install dependencies
      run: composer install --no-progress

    - name: Format check
      run: make cs

    - name: Static analysis
      run: make stan

    - name: Tests
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        files: coverage/clover.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Test examples
      run: make test-examples
